/* Historial de Recepción de Propiedades, transcripto desde "Recepción de propiedades.docx".
   Los 5 registros más recientes del documento original estaban todos numerados "N°46" por error
   de tipeo del equipo; aquí se renumeraron correlativamente (50 a 46) y se deja la aclaración en
   `notas`. El N°17 y el N°31 no existen en el documento original (se ve que se eliminaron). */
export const receptionSeed = [
  {
    num: 50,
    responsable: 'Fabiana',
    owner: 'Karina',
    phone: '1151077755',
    fecha: '11/6/26',
    propiedad: 'Calle 45 entre Punta del Indio y Pinamar',
    tasacion: 'si, Silvia y Pablo',
    valor: 'Usd',
    autorizacion: 'si, Pablo',
    cartel: 'si',
    fotos: 'si',
    descripcion: 'falta',
    notas: 'Numeración original del documento: N°46 (primero de 5 registros cargados con ese mismo número por error de tipeo).',
  },
  {
    num: 49,
    responsable: 'Pablo',
    owner: 'Natalia Corro',
    phone: '1160378899',
    fecha: '6/6/26',
    propiedad: 'Calle 42 entre Av 1 y Punta del Este',
    tasacion: 'si, Silvia y Pablo',
    valor: 'Usd 250.000',
    autorizacion: 'si, Pablo',
    cartel: 'si',
    fotos: 'si',
    descripcion: 'falta',
    link: 'https://www.silviafernandezpropiedades.com.ar/propiedad/8170756',
    notas: 'Numeración original del documento: N°46 (segundo de 5 registros cargados con ese mismo número por error de tipeo).',
  },
  {
    num: 48,
    responsable: 'Fabiana',
    owner: 'Sabrina Romero',
    phone: '1130445175',
    fecha: '8/6/26',
    propiedad: 'Lote Pinamar e/ 34 y 35 - Mz. 270, Parc. 32',
    superficie: '350 m² (lote)',
    tasacion: 'si, Silvia y Pablo',
    valor: 'Usd 32.000',
    notas: 'Responsable en proceso. Numeración original del documento: N°46 (tercero de 5 registros cargados con ese mismo número por error de tipeo).',
  },
  {
    num: 47,
    responsable: 'Cecilia',
    owner: 'Marilyn',
    phone: '2216125155',
    fecha: '06/06/26',
    propiedad: 'Lote Punta del Este e/ 39 y 40',
    tasacion: 'Silvia y Pablo',
    valor: 'Usd 45.000',
    autorizacion: 'si, Paul',
    cartel: 'sí, Pablo',
    fotos: 'sí, Paul',
    descripcion: 'sí',
    notas: 'Hay que pedir llaves del candado para mostrarlo. Numeración original del documento: N°46 (cuarto de 5 registros cargados con ese mismo número por error de tipeo).',
  },
  {
    num: 46,
    responsable: 'Paul',
    owner: 'Maria Cecilia Goyeneche',
    phone: '2494-469615',
    fecha: '06/06/26',
    propiedad: 'Chacras del Mar Etapa 1-2 Dpto 14 PB',
    tasacion: 'Silvia y Pablo',
    valor: 'Usd 160.000',
    autorizacion: 'si, Paul',
    cartel: 'No llevan ahí',
    fotos: 'falta sacar',
    descripcion: 'no',
    notas: 'Numeración original del documento: N°46 (quinto de 5 registros cargados con ese mismo número por error de tipeo).',
  },
  {
    num: 45,
    responsable: 'Fabiana',
    owner: 'Maximiliano',
    phone: '1154856760',
    fecha: '2/06',
    propiedad: 'Calle 32 entre Punta del Indio y Pinamar',
    tasacion: 'Silvia y Pablo',
    valor: 'Usd 130.000',
    autorizacion: 'SI, Faby',
    cartel: 'si',
    fotos: 'falta sacar, mientras tanto subimos con las que mandó el dueño',
    descripcion: 'si',
    link: 'https://www.silviafernandezpropiedades.com.ar/propiedad/8148292',
  },
  {
    num: 44,
    responsable: 'Conrado',
    owner: 'Vanina',
    fecha: '28/5',
    propiedad: 'Lote - Punta del Este e/ 36 y 37',
    tasacion: 'Silvia y Pablo',
    valor: 'usd 50.000',
    autorizacion: 'no hace falta, no hay exclusividad',
    cartel: 'no, tiene cartel de Soria Roncoroni',
    fotos: 'sí, Curly',
    descripcion: 'sí, Curly',
  },
  {
    num: 43,
    responsable: 'Fabiana',
    owner: 'Ana Alfageme',
    fecha: '29/5',
    propiedad: 'Dpto - Edificio "Arena Azul" - Brown y Mar del Plata - Gaviotas',
    tasacion: 'Silvia y Pablo',
    valor: 'USD 135.000.-',
    autorizacion: 'SI',
    cartel: 'No llevaba cartel',
    fotos: 'SI',
    descripcion: 'sí, Ceci',
  },
  {
    num: 42,
    responsable: 'Fabiana',
    owner: 'Jorge Marsiglione',
    phone: '1144288134',
    fecha: '22/5',
    propiedad: 'Dpto Calle 32 e/ Mar Azul y Mar del Plata',
    tasacion: 'Si, Silvia y Pablo',
    valor: 'Usd 125.000.-',
    autorizacion: 'si',
    cartel: 'si, (Pablo y Conra)',
    fotos: 'si, Conra',
    descripcion: 'si',
    link: 'https://www.silviafernandezpropiedades.com.ar/propiedad/8095003',
  },
  {
    num: 41,
    responsable: 'Cecilia',
    owner: 'Martín Bolpe (2215641150) y Alejandra Alcalde',
    fecha: '21-05-26',
    propiedad: 'Lote Gaviotas. Necochea entre 28 y 29',
    tasacion: 'USD 55.000',
    valor: 'USD 55.000',
    autorizacion: 'en proceso, a la espera de respuesta del dueño',
  },
  {
    num: 40,
    responsable: 'Conrado',
    owner: 'Carlos Alfinito',
    phone: '1131631885',
    fecha: '21/05/2026',
    propiedad: '5 lotes en Mar Azul: lote 3 y 4 mz 360 (usurpado), 325 lote 1 y 7, 358 lote 17',
    tasacion: 'Pablo y Silvia',
    valor: 'lote 3 mz 360 usd 32.000, lote 17 mz 358 usd 32.000, lote 7 mz 325 usd 38.000 y lote 1 mz 325 usd 27.000',
    autorizacion: 'Faby',
    cartel: 'Sí a los 4 lotes, Conrado y Pablo',
    fotos: 'Si',
    descripcion: 'Si',
  },
  {
    num: 39,
    responsable: 'Paul',
    owner: 'Leonardo',
    phone: '11-6870-2510',
    fecha: '15/05/26',
    propiedad: 'San Clemente del Tuyú e/ 34 y 35',
    tasacion: 'no',
    valor: 'la vende hasta usd 56.000',
    autorizacion: 'si, Paul',
    cartel: 'si, Pablo y Conrado',
    fotos: 'subir a Tokko como "tasación", como publicación interna',
    descripcion: 'si',
  },
  {
    num: 38,
    responsable: 'Conrado',
    owner: 'Selva Cespedes',
    phone: '2255602964',
    fecha: '15/05/26',
    propiedad: '32 y Monte Hermoso',
    tasacion: 'si',
    valor: 'USD 120.000.-',
    autorizacion: 'pendiente',
  },
  {
    num: 37,
    responsable: 'Pablo',
    owner: 'Veronica Gonzalez (1168497648) - Eduardo Chechile (1168497603)',
    fecha: '12/05/26',
    propiedad: 'Casa "Alma Mater" - Lola Mora y Storni',
    tasacion: 'Silvia',
    valor: 'USD 189.000.-',
    autorizacion: 'si, Pablo',
    cartel: 'sí, Pablo',
    fotos: 'SI',
    descripcion: 'si',
    link: 'https://www.silviafernandezpropiedades.com.ar/propiedad/8054995',
  },
  {
    num: 36,
    responsable: 'Fabiana',
    owner: 'Marcela Ovando',
    phone: '2255408040',
    fecha: '9/5/26',
    propiedad: 'Local - Punta del Este esquina 34',
    tasacion: 'Silvia',
    valor: 'USD 200.000',
    autorizacion: 'no se hace',
    cartel: 'si, Pablo',
    fotos: 'si, Conrado',
    descripcion: 'sí',
    link: 'https://www.silviafernandezpropiedades.com.ar/propiedad/8042506',
    notas: 'El 31/7/26 el inquilino paga U$D 17.000.- y el 31/07/27 paga U$D 19.000.-',
  },
  {
    num: 35,
    responsable: 'Pablo',
    owner: 'Marisol García',
    phone: '11 61165393',
    fecha: '08-05-26',
    propiedad: 'Viña del Mar y calle 44 "Fuerzas del Mar"',
    superficie: 'Sup. total 333 m² - Sup. cub. 60 m²',
    tasacion: 'Silvia y Cecilia',
    valor: 'USD 100.000.-',
    autorizacion: 'si',
    cartel: 'SI',
    fotos: 'si',
    descripcion: 'si',
    link: 'https://www.silviafernandezpropiedades.com.ar/propiedad/8063528',
    notas: 'Tiene alarma y llave digital.',
  },
  {
    num: 34,
    responsable: 'Fabiana',
    owner: 'Amigo de Ricardo Chipolla',
    fecha: '06-05-26',
    propiedad: 'Casa 42 e/ Necochea y Pinamar. Mar Azul',
    tasacion: 'Silvia',
    pausa: true,
    notas: 'En pausa.',
  },
  {
    num: 33,
    responsable: 'Pablo',
    fecha: '06-05-26',
    propiedad: 'Duplex Av 4 n°4638 entre 146 y 146 bis. Villa Gesell',
    tasacion: 'Silvia y Ceci',
    valor: 'USD 58.000',
    pausa: true,
    notas: 'Queda en pausa.',
  },
  {
    num: 32,
    responsable: 'Fabiana',
    owner: 'Dario',
    phone: '1127001099',
    fecha: '02-05-26',
    propiedad: 'Casa - Calle 37 entre Mar del Plata y Punta del Este',
    tasacion: 'Silvia y Ceci',
    autorizacion: 'no',
    cartel: 'no',
    fotos: 'no aún',
    descripcion: 'no',
  },
  {
    num: 30,
    responsable: 'Fabiana',
    owner: 'Federico Boco',
    phone: '1134935991',
    fecha: '02-05-26',
    propiedad: 'Lote 35 e/ Miramar y Necochea, Mz 279, Parcela 9',
    superficie: '10x47,5 (lote)',
    tasacion: 'Silvia',
    valor: 'USD 36.000',
    autorizacion: 'SI',
    cartel: 'se encarga Conrado, le están haciendo un alambrado; en dos días lo terminan y ahí pone el cartel (dicho por el dueño)',
    fotos: 'no aún, le están haciendo un alambrado; en dos días lo terminan y ahí sacamos las fotos (dicho por el dueño)',
    descripcion: 'no',
    pausa: true,
    notas: 'Suspendido hasta nuevo aviso.',
  },
  {
    num: 29,
    responsable: 'Fabiana',
    owner: 'Adrián',
    phone: '1153071250',
    fecha: '02-05-26',
    propiedad: 'Pasaje Blanca n°32 esquina Juan Repetto',
    tasacion: 'Silvia y Ceci',
    pausa: true,
    notas: 'Cuñado de Fernando Bigi. Queda en suspenso.',
  },
  {
    num: 28,
    responsable: 'Fabiana',
    owner: 'Fernando Bigi',
    phone: '1158375764',
    fecha: '02-05-26',
    propiedad: '34 e/ Mar del Plata y Mar Azul "Sol Azul"',
    tasacion: 'Silvia y Ceci, 14:00 hs',
    valor: 'USD 300.000',
    autorizacion: 'en proceso de aprobación',
  },
  {
    num: 27,
    responsable: 'Cecilia',
    owner: 'Mirna',
    fecha: '25-04-26',
    propiedad: 'Necochea N°731 e/ 34 y 35',
    tasacion: 'Silvia y Ceci',
    valor: 'USD 140.000 (se vende sin muebles)',
    autorizacion: 'sí',
    cartel: 'Sí, Conrado',
    fotos: 'sí, Arom',
    descripcion: 'sí, Ceci',
  },
  {
    num: 26,
    responsable: 'Conrado',
    owner: 'Oscar Dipaola',
    fecha: '22-04-26',
    propiedad: 'Complejo "Pampa Mansa" Av del Plata e/ Calampayo y los Cóndores',
    tasacion: 'a cargo de Silvia',
    valor: 'usd 680.000',
    autorizacion: 'no',
    cartel: 'no',
    fotos: 'sí, Conrado',
    descripcion: 'sí, Conrado y Ceci supervisó',
  },
  {
    num: 25,
    responsable: 'Paul',
    owner: 'Emanuel',
    fecha: '21-04-26',
    propiedad: 'Complejo "Runa Moraira" Victoria entre Virazón y Sosa',
    tasacion: '22-04, 17hs. Silvia y Pablo',
    valor: 'no',
    autorizacion: 'el dueño lo va a trabajar de forma particular',
    cartel: 'no',
    fotos: 'no',
    descripcion: 'no',
    pausa: true,
    notas: 'Queda en suspenso.',
  },
  {
    num: 24,
    responsable: 'Paul',
    fecha: '21-04-26',
    propiedad: 'Fondo de comercio "El Nido"',
    tasacion: 'No',
    valor: '$ 40.000.000',
    autorizacion: 'no, porque es una ayuda al propietario',
    cartel: 'no se pone',
    fotos: 'si, Arom',
    descripcion: 'Si, Paul',
  },
  {
    num: 23,
    responsable: 'Fabiana',
    owner: 'Guillermo Zukowski',
    phone: '1134748804',
    fecha: '20/04',
    propiedad: 'Lote Punta del Este e/ 40 y 41',
    tasacion: 'Silvia y Pablo',
    valor: 'USD 45.000',
    autorizacion: 'Si, Faby',
    cartel: 'si, Pablo',
    fotos: 'si',
    descripcion: 'si',
    link: 'https://www.silviafernandezpropiedades.com.ar/propiedad/7962268',
  },
  {
    num: 22,
    responsable: 'Fabiana',
    fecha: '18-04-26',
    propiedad: 'Condominios Solares. Unidad n°29',
    tasacion: 'Silvia y Pablo',
    valor: 'USD 130.000',
    autorizacion: 'sí, firmada (está en el grupo de WhatsApp)',
    cartel: 'no lleva cartel',
    fotos: 'si',
    descripcion: 'si',
    link: 'https://www.silviafernandezpropiedades.com.ar/propertyDetail/7992332',
  },
  {
    num: 21,
    responsable: 'Pablo',
    owner: 'Marcela A. Quinteros',
    fecha: '17-04-26',
    propiedad: '43 e/ Punta del Este y 1 (una casa arriba y otra abajo)',
    tasacion: 'si, Silvia y Pablo',
    valor: '175.000',
    autorizacion: 'sí',
    cartel: 'sí, Pablo',
    fotos: 'sí, Pablo',
    descripcion: 'sí, Ceci',
  },
  {
    num: 20,
    responsable: 'Cecilia',
    fecha: '16-04-26',
    propiedad: 'Apart Fueguia. Santa Maria 444 e/ El Ceibo y Garay Pampas',
    tasacion: 'si, Silvia y Pablo',
    valor: 'Usd 650.000',
    autorizacion: 'no',
    cartel: 'no se pone cartel porque el dueño no quiere',
    fotos: 'sí, Fabi. Hay que sacar más.',
    descripcion: 'sí, Ceci',
  },
  {
    num: 19,
    fecha: '13-04-26',
    propiedad: '40 entre San Clemente y Monte Hermoso n°1027 (casa naranja)',
    tasacion: 'se hizo la tasación, esperando confirmación del dueño',
    valor: '85.000 usd',
    pausa: true,
    notas: 'Queda en suspenso.',
  },
  {
    num: 18,
    responsable: 'Pablo',
    fecha: '12-04-26',
    propiedad: 'Lote San Clemente e/ 29 y 30',
    tasacion: 'sí',
    valor: 'USD 40.000',
    autorizacion: 'no, porque es amigo de Pablo',
    cartel: 'sí, Pablo',
    fotos: 'sí, Pablo',
    descripcion: 'sí, Ceci',
  },
  {
    num: 16,
    responsable: 'Curly',
    fecha: '10-04',
    propiedad: 'Complejo de cabañas en 30 e/ Mar Azul y playa Ciromare',
    tasacion: 'Silvia',
    valor: '1.500.000',
    autorizacion: 'si',
    cartel: 'no se pone',
    fotos: 'si',
    descripcion: 'sí',
    notas: 'Complejo Ciromare. Título de publicación: "Complejo | Silvia Fernández Inmobiliaria".',
  },
  {
    num: 15,
    owner: 'Guillermina Vacaz',
    fecha: '09-04',
    propiedad: 'Punta del Indio e/ 34 y 35',
    tasacion: 'Silvia y Pablo',
    valor: 'USD 67.000',
    autorizacion: 'los dueños evalúan si ponerla a la venta',
  },
  {
    num: 14,
    fecha: '09-04',
    propiedad: 'Calle 40 e/ Viña del Mar y Copacabana ("Mustang Ranch")',
    idPublicacion: '6759059',
    valor: 'Usd 120.000 la casa y USD 45.000 el lote',
    autorizacion: 'sí',
    cartel: 'sí, Conrado',
    fotos: 'Sí',
    descripcion: 'de lote, hecha a cargo de Pablo. Casa: descripción de Ceci',
    notas: 'Propiedad vieja que ahora se debe publicar por separado: el lote y la casa.',
  },
  {
    num: 13,
    responsable: 'Conrado',
    fecha: '09-04',
    propiedad: 'Departamento en Las Gaviotas, "Solari y las Gaviotas"',
    tasacion: 'Silvia y Pablo',
    valor: 'Usd 130.000',
    autorizacion: 'ya está',
    fotos: 'pablo ya sacó las fotos',
    descripcion: 'con',
    link: 'https://www.silviafernandezpropiedades.com.ar/propiedad/7992332',
  },
  {
    num: 12,
    fecha: '06-04-26',
    propiedad: 'Lote nuevo en Pampas! Av del Plata e/ Sta María y Querandíes',
    tasacion: 'Silvia',
    valor: 'USd 50.000',
    autorizacion: 'sí, Silvia',
    cartel: 'sí, Conrado',
    fotos: 'Sí, Pablo',
    descripcion: 'sí, Pablo',
  },
  {
    num: 11,
    fecha: '04-04-26',
    propiedad: 'José Ingenieros n°17 (Mar de las Pampas)',
    tasacion: 'Silvia',
    valor: 'USD 220.000',
    autorizacion: 'Sí, Paul',
    cartel: 'Sí, Conrado',
    fotos: 'Sí, Pablo',
    descripcion: 'Sí, Arom',
  },
  {
    num: 10,
    fecha: '01-04-26',
    propiedad: 'Calle 36 y Punta del Indio',
    tasacion: 'Pablo',
    valor: 'USD 139.000',
    autorizacion: 'si, Pablo',
    cartel: 'sí',
    fotos: 'Sí. Pablo sacó fotos y video.',
    descripcion: 'sí, Arom',
  },
  {
    num: 9,
    fecha: 'Marzo',
    propiedad: 'La Elegida (complejo). Calle 41 e/ Punta del Indio y Viña del Mar',
    tasacion: 'Silvia y Pablo',
    valor: 'USD 650.000',
    autorizacion: 'Sí, Silvia',
    cartel: 'no se pone (los dueños no quieren que se enteren los empleados)',
    fotos: 'sí, Pablo',
    descripcion: 'sí, Ceci',
  },
  {
    num: 8,
    fecha: '28-03-26',
    propiedad: 'Cariló. Cerezo n°731',
    tasacion: 'Silvia y Pablo',
    valor: 'Usd 230.000',
    autorizacion: 'por ahora no se va a hacer',
    cartel: 'si, Paul',
    fotos: 'Sí, Pablo',
    descripcion: 'Sí, Ceci',
  },
  {
    num: 7,
    fecha: '27-03-26',
    propiedad: 'Copacabana e/ 39 y 40 (tranquera blanca)',
    tasacion: 'Silvia y Pablo',
    pausa: true,
    notas: 'Todavía no decidió venderla con nosotros. Suspendido hasta nuevo aviso.',
  },
  {
    num: 6,
    fecha: '26-03-26',
    propiedad: '36 e/ Necochea y Miramar',
    tasacion: 'Pablo. Hay que sacar foto y ratificar valor.',
    autorizacion: 'Pablo la tiene que hacer',
    fotos: 'Pablo tiene que sacar las fotos, aún no están',
    notas: 'Hay video en equipo. La dueña dijo que lo tiene que pensar con el marido y nos avisa.',
  },
  {
    num: 5,
    fecha: '24-03',
    propiedad: 'Copacabana e/ 34 y 35 (Mar Azul). 2 chalets contiguos',
    idPublicacion: '7876191',
    tasacion: 'Silvia',
    valor: 'Usd 147.000',
    autorizacion: 'sí (impresa en Mar Azul)',
    cartel: 'sí',
    fotos: 'sí, Arom',
    descripcion: 'sí, Arom',
  },
  {
    num: 4,
    responsable: 'Cecilia',
    owner: 'Daniel y Margarita',
    phone: '1153233826',
    fecha: '24-03-26',
    propiedad: '44 e/ Mar Azul y Mar del Plata (2 casas)',
    superficie: 'Sup. cub. 240,91 m² - Lote 950 m²',
    tasacion: 'Silvia',
    valor: 'Usd 250.000',
    autorizacion: 'Sí, firmada',
    cartel: 'la dueña no quiere que le coloquen cartel',
    fotos: 'Sí, Arom y Pablo (Conrado le envió a Arom un link con fotos)',
    descripcion: 'sí',
    notas: 'Hay que volver a sacar fotos, aún no hay llaves. Se comunicó con la dueña el 18/05; dentro de 15 días viene el marido.',
  },
  {
    num: 3,
    owner: 'Cristina',
    fecha: '24-03-26',
    propiedad: 'Necochea e/ 43 y 44',
    superficie: 'Sup. cub. 86,16 m² - Lote 350 m²',
    tasacion: 'Silvia y Pablo',
    valor: 'Usd 145.000',
    autorizacion: 'sí, firmada',
    cartel: 'si, Pablo',
    fotos: 'sí, Pablo',
    descripcion: 'sí, Cecilia',
    notas: 'Alejandra mostró la casa.',
  },
  {
    num: 2,
    responsable: 'Cecilia',
    owner: 'Maxi',
    fecha: '25-03-26',
    propiedad: 'Copacabana e/ 43 y 44',
    idPublicacion: '7886629',
    tasacion: 'Silvia y Pablo',
    valor: 'USD 125.000',
    autorizacion: 'a cargo de Silvia',
    cartel: 'Sí, Conrado',
    fotos: 'sí',
    descripcion: 'sí',
  },
  {
    num: 1,
    responsable: 'Cecilia',
    fecha: '20-03-26',
    propiedad: 'Complejo. Calle 35 e/ Copacabana y Punta del Este. 7 cabañas',
    valor: 'USD 650.000',
    autorizacion: 'a cargo de Silvia',
    cartel: 'sí, Conrado',
    fotos: 'sí',
    descripcion: 'sí',
  },
];
