/* Datos reales de Recepción de Propiedades (carga inicial) */
export const receptionSeed = [
 {
  "num": 46,
  "responsable": "Cecilia",
  "respColor": "#7257c9",
  "respInit": "C",
  "owner": "Marilyn",
  "phone": "2216125155",
  "fecha": "06/06/26",
  "propiedad": "Lote punta del este e/39 y 40",
  "valor": "Usd 45.000",
  "autorizacion": "si, Paul en proceso",
  "cartel": "",
  "fotos": "",
  "descripcion": "",
  "tasacion": "Silvia y Pablo",
  "link": "",
  "flags": [],
  "steps": {
   "tasacion": "done",
   "autorizacion": "missing",
   "cartel": "missing",
   "fotos": "missing",
   "descripcion": "missing"
  },
  "status": "celeste"
 },
 {
  "num": 46,
  "responsable": "Paul",
  "respColor": "#0e8a8a",
  "respInit": "P",
  "owner": "Maria Cecilia Goyeneche",
  "phone": "2494- 469615",
  "fecha": "06/06/26",
  "propiedad": "Chacras del Mar Etapa 1-2 Dpto 14 PB",
  "valor": "Usd 160.000",
  "autorizacion": "si, Paul",
  "cartel": "No llevan ahí",
  "fotos": "falta sacar",
  "descripcion": "no",
  "tasacion": "Silvia y Pablo",
  "link": "",
  "flags": [],
  "steps": {
   "tasacion": "done",
   "autorizacion": "done",
   "cartel": "na",
   "fotos": "missing",
   "descripcion": "missing"
  },
  "status": "rojo"
 },
 {
  "num": 45,
  "responsable": "Fabiana",
  "respColor": "#c2861a",
  "respInit": "F",
  "owner": "Maximiliano",
  "phone": "1154856760",
  "fecha": "2/06",
  "propiedad": "Calle 32 entre Punta del Indio y Pinamar",
  "valor": "Usd 130.000",
  "autorizacion": "SI, Faby",
  "cartel": "si",
  "fotos": "falta sacar, mientras tanto subimos con las que mandó el dueño",
  "descripcion": "https://www.silviafernandezpropiedades.com.ar/propiedad/8148292",
  "tasacion": "Silvia y Pablo",
  "link": "https://www.silviafernandezpropiedades.com.ar/propiedad/8148292",
  "flags": [],
  "steps": {
   "tasacion": "done",
   "autorizacion": "done",
   "cartel": "done",
   "fotos": "missing",
   "descripcion": "partial"
  },
  "status": "rojo"
 },
 {
  "num": 45,
  "responsable": "Pablo",
  "respColor": "#2563eb",
  "respInit": "P",
  "owner": "Natalia",
  "phone": "1160022757",
  "fecha": "01/06",
  "propiedad": "Casa- Viña e/ 34 y 35",
  "valor": "Usd 95.000",
  "autorizacion": "SI, Pablo",
  "cartel": "no",
  "fotos": "falta sacar",
  "descripcion": "",
  "tasacion": "Silvia y Pablo",
  "link": "",
  "flags": [],
  "steps": {
   "tasacion": "done",
   "autorizacion": "done",
   "cartel": "missing",
   "fotos": "missing",
   "descripcion": "missing"
  },
  "status": "rojo"
 },
 {
  "num": 44,
  "responsable": "Conrado",
  "respColor": "#15784f",
  "respInit": "C",
  "owner": "Vanina",
  "phone": "",
  "fecha": "28/5",
  "propiedad": "Lote - Punta del Este e/ 36 y 37",
  "valor": "usd 50.000",
  "autorizacion": "no hace falta, no hay exclusividad",
  "cartel": "no, tiene cartel de soria roncoroni",
  "fotos": "curly",
  "descripcion": "curly",
  "tasacion": "Silvia y Pablo",
  "link": "",
  "flags": [],
  "steps": {
   "tasacion": "done",
   "autorizacion": "na",
   "cartel": "missing",
   "fotos": "partial",
   "descripcion": "partial"
  },
  "status": "rojo"
 },
 {
  "num": 43,
  "responsable": "Fabiana",
  "respColor": "#c2861a",
  "respInit": "F",
  "owner": "Ana Alfageme",
  "phone": "",
  "fecha": "29/5",
  "propiedad": "Dpto - Edificio “Arena Azul” - Brown y Mar del Plata - Gaviotas",
  "valor": "USD 135.000.-",
  "autorizacion": "SI",
  "cartel": "No llevaba cartel",
  "fotos": "SI",
  "descripcion": "sí, Ceci",
  "tasacion": "Silvia y Pablo",
  "link": "",
  "flags": [],
  "steps": {
   "tasacion": "done",
   "autorizacion": "done",
   "cartel": "na",
   "fotos": "done",
   "descripcion": "done"
  },
  "status": "negro"
 },
 {
  "num": 42,
  "responsable": "Fabiana",
  "respColor": "#c2861a",
  "respInit": "F",
  "owner": "Jorge Marsiglione",
  "phone": "1144288134",
  "fecha": "22/5",
  "propiedad": "dpto Calle 32 e/ Mar Azul y Mar del Plata",
  "valor": "Usd 125.000.-",
  "autorizacion": "si",
  "cartel": "si, (Pablo y Conra)",
  "fotos": "si, Conra",
  "descripcion": "si, https://www.silviafernandezpropiedades.com.ar/propiedad/8095003",
  "tasacion": "Si, Silvia y Pablo",
  "link": "https://www.silviafernandezpropiedades.com.ar/propiedad/8095003",
  "flags": [],
  "steps": {
   "tasacion": "done",
   "autorizacion": "done",
   "cartel": "done",
   "fotos": "done",
   "descripcion": "done"
  },
  "status": "negro"
 },
 {
  "num": 41,
  "responsable": "Cecilia",
  "respColor": "#7257c9",
  "respInit": "C",
  "owner": "Martín Bolpe y Alejandra Alcalde",
  "phone": "2215641150",
  "fecha": "21-05-26",
  "propiedad": "Lote gaviotas. Necochea entre 28 y 29",
  "valor": "USD 55.000",
  "autorizacion": "en proceso",
  "cartel": "",
  "fotos": "",
  "descripcion": "",
  "tasacion": "USD 55.000",
  "link": "",
  "flags": [],
  "steps": {
   "tasacion": "partial",
   "autorizacion": "missing",
   "cartel": "missing",
   "fotos": "missing",
   "descripcion": "missing"
  },
  "status": "celeste"
 },
 {
  "num": 40,
  "responsable": "Conrado",
  "respColor": "#15784f",
  "respInit": "C",
  "owner": "Carlos Alfinito",
  "phone": "1131631885",
  "fecha": "21/05/2026",
  "propiedad": "5 lotes en Mar Azul:lote 3 y 4 mz 360 (usurp), 325 lote 1 y 7, 358 lote 17",
  "valor": "lote 3 mz 360 usd 32.000, lote 17 mz 358 usd32.000, lote 7 mz 325 usd 38.000 y lote 1 mz 325 usd27.000.",
  "autorizacion": "Faby",
  "cartel": "Sí a los 4 lotes. Con y Pablo",
  "fotos": "Si",
  "descripcion": "Si",
  "tasacion": "Pablo y Silvia",
  "link": "",
  "flags": [],
  "steps": {
   "tasacion": "done",
   "autorizacion": "done",
   "cartel": "done",
   "fotos": "done",
   "descripcion": "done"
  },
  "status": "negro"
 },
 {
  "num": 39,
  "responsable": "Paul",
  "respColor": "#0e8a8a",
  "respInit": "P",
  "owner": "Leonardo",
  "phone": "11-6870-2510",
  "fecha": "15/05/26",
  "propiedad": "San Clemente del tuyú e/34 y 35",
  "valor": "la vende hasta usd 56.000",
  "autorizacion": "si Paul",
  "cartel": "si Pablo y Conrado",
  "fotos": "(subir a tokko como “tasación” COMO PUBLICACIÓN INTERNA)",
  "descripcion": "si",
  "tasacion": "no",
  "link": "",
  "flags": [],
  "steps": {
   "tasacion": "missing",
   "autorizacion": "done",
   "cartel": "done",
   "fotos": "partial",
   "descripcion": "done"
  },
  "status": "rojo"
 },
 {
  "num": 38,
  "responsable": "Conrado",
  "respColor": "#15784f",
  "respInit": "C",
  "owner": "Selva Cespedes",
  "phone": "2255602964",
  "fecha": "15/05/26",
  "propiedad": "32 y monte hermoso",
  "valor": "USD 120.000.-",
  "autorizacion": "pendiente",
  "cartel": "",
  "fotos": "",
  "descripcion": "",
  "tasacion": "si",
  "link": "",
  "flags": [],
  "steps": {
   "tasacion": "done",
   "autorizacion": "missing",
   "cartel": "missing",
   "fotos": "missing",
   "descripcion": "missing"
  },
  "status": "celeste"
 },
 {
  "num": 37,
  "responsable": "Pablo",
  "respColor": "#2563eb",
  "respInit": "P",
  "owner": "Veronica Gonzalez - Eduardo Chechile 1168497603",
  "phone": "1168497648",
  "fecha": "12/05/26",
  "propiedad": "CASA “ALMA MATER” - Lola Mora y Storni",
  "valor": "USD 189.000.-",
  "autorizacion": "si, Pablo",
  "cartel": "sí, Pablo",
  "fotos": "SI",
  "descripcion": "si, https://www.silviafernandezpropiedades.com.ar/propiedad/8054995",
  "tasacion": "Silvia",
  "link": "https://www.silviafernandezpropiedades.com.ar/propiedad/8054995",
  "flags": [],
  "steps": {
   "tasacion": "done",
   "autorizacion": "done",
   "cartel": "done",
   "fotos": "done",
   "descripcion": "done"
  },
  "status": "negro"
 },
 {
  "num": 36,
  "responsable": "Fabiana",
  "respColor": "#c2861a",
  "respInit": "F",
  "owner": "Marcela Ovando",
  "phone": "2255408040",
  "fecha": "9/5/26",
  "propiedad": "LOCAL - Punta del Este esquina 34",
  "valor": "USD 200.000",
  "autorizacion": "no se hace",
  "cartel": "si, Pablo -",
  "fotos": "si, Conrado",
  "descripcion": "https://www.silviafernandezpropiedades.com.ar/propiedad/8042506 el 31/7/26 inquilino paga U$D 17.000.- 31/07/27 paga U$D 19.000.-",
  "tasacion": "Silvia",
  "link": "https://www.silviafernandezpropiedades.com.ar/propiedad/8042506",
  "flags": [],
  "steps": {
   "tasacion": "done",
   "autorizacion": "na",
   "cartel": "done",
   "fotos": "done",
   "descripcion": "partial"
  },
  "status": "negro"
 },
 {
  "num": 35,
  "responsable": "Pablo",
  "respColor": "#2563eb",
  "respInit": "P",
  "owner": "Marisol García",
  "phone": "11 61165393",
  "fecha": "08-05-26",
  "propiedad": "Viña del mar y calle 44 “Fuerzas del Mar” (tiene alarma y llave digital)",
  "valor": "USD 100.000.-",
  "autorizacion": "si",
  "cartel": "SI",
  "fotos": "si",
  "descripcion": "si sup total 333 m² - sup cub 60 m² https://www.silviafernandezpropiedades.com.ar/propiedad/8063528",
  "tasacion": "Silvia y Cecilia",
  "link": "https://www.silviafernandezpropiedades.com.ar/propiedad/8063528",
  "flags": [],
  "steps": {
   "tasacion": "done",
   "autorizacion": "done",
   "cartel": "done",
   "fotos": "done",
   "descripcion": "done"
  },
  "status": "negro"
 },
 {
  "num": 34,
  "responsable": "Fabiana",
  "respColor": "#c2861a",
  "respInit": "F",
  "owner": "amigo de Ricardo Chipolla",
  "phone": "",
  "fecha": "06-05-26",
  "propiedad": "CASA 42 e/ Necochea y Pinamar. MAR AZUL",
  "valor": "USD",
  "autorizacion": "",
  "cartel": "",
  "fotos": "",
  "descripcion": "",
  "tasacion": "Silvia",
  "link": "",
  "flags": [
   "pausa"
  ],
  "steps": {
   "tasacion": "done",
   "autorizacion": "missing",
   "cartel": "missing",
   "fotos": "missing",
   "descripcion": "missing"
  },
  "status": "pausa"
 },
 {
  "num": 33,
  "responsable": "Pablo",
  "respColor": "#2563eb",
  "respInit": "P",
  "owner": "",
  "phone": "",
  "fecha": "06-05-26",
  "propiedad": "DUPLEX av 4 n 4638 entre 146 y 146 bis. VILLA GESELL",
  "valor": "USD 58.000",
  "autorizacion": "",
  "cartel": "",
  "fotos": "",
  "descripcion": "",
  "tasacion": "Silvia y Ceci",
  "link": "",
  "flags": [
   "pausa"
  ],
  "steps": {
   "tasacion": "done",
   "autorizacion": "missing",
   "cartel": "missing",
   "fotos": "missing",
   "descripcion": "missing"
  },
  "status": "pausa"
 },
 {
  "num": 32,
  "responsable": "Fabiana",
  "respColor": "#c2861a",
  "respInit": "F",
  "owner": "Dario",
  "phone": "1127001099",
  "fecha": "02-05-26",
  "propiedad": "CASA - Calle 37 entre Mar del Plata y Punta del Este.",
  "valor": "USD",
  "autorizacion": "no",
  "cartel": "no",
  "fotos": "no aun",
  "descripcion": "no",
  "tasacion": "Silvia y Ceci",
  "link": "",
  "flags": [],
  "steps": {
   "tasacion": "done",
   "autorizacion": "missing",
   "cartel": "missing",
   "fotos": "missing",
   "descripcion": "missing"
  },
  "status": "rojo"
 },
 {
  "num": 30,
  "responsable": "Fabiana",
  "respColor": "#c2861a",
  "respInit": "F",
  "owner": "Federico Boco",
  "phone": "1134935991",
  "fecha": "02-05-26",
  "propiedad": "LOTE, 35 e/ Miramar y Necochea, Mz 279, Parcela 9, 10x47,5",
  "valor": "USD 36.000",
  "autorizacion": "SI",
  "cartel": "se encarga Con, estan haciendole un alambrado, en dos días lo terminan y ahí pone cartel (dicho por el dueño)",
  "fotos": "no aun, estan haciendole un alambrado, en dos dias lo terminan  y ahí sacamos la fotos (dicho por el dueño)",
  "descripcion": "no",
  "tasacion": "Silvia",
  "link": "",
  "flags": [
   "suspendido"
  ],
  "steps": {
   "tasacion": "done",
   "autorizacion": "done",
   "cartel": "done",
   "fotos": "missing",
   "descripcion": "missing"
  },
  "status": "pausa"
 },
 {
  "num": 29,
  "responsable": "Fabiana",
  "respColor": "#c2861a",
  "respInit": "F",
  "owner": "",
  "phone": "",
  "fecha": "02-05-26 - ADRIAN - cel 1153071250",
  "propiedad": "Pasaje Blanca n°32 esquina Juan Repetto (cuñado Fernando Bigi)",
  "valor": "USD",
  "autorizacion": "",
  "cartel": "",
  "fotos": "",
  "descripcion": "",
  "tasacion": "Silvia y Ceci",
  "link": "",
  "flags": [
   "suspendido"
  ],
  "steps": {
   "tasacion": "done",
   "autorizacion": "missing",
   "cartel": "missing",
   "fotos": "missing",
   "descripcion": "missing"
  },
  "status": "pausa"
 },
 {
  "num": 28,
  "responsable": "Fabiana",
  "respColor": "#c2861a",
  "respInit": "F",
  "owner": "",
  "phone": "",
  "fecha": "02-05-26 - Fernando Bigi - Cel 1158375764",
  "propiedad": "34 e/mar del plata y mar azul “Sol azul” (Fernando Bigi)",
  "valor": "USD 300.000",
  "autorizacion": "en proceso de aprobación",
  "cartel": "",
  "fotos": "",
  "descripcion": "",
  "tasacion": "Silvia y Ceci. 14.00 hs",
  "link": "",
  "flags": [],
  "steps": {
   "tasacion": "done",
   "autorizacion": "missing",
   "cartel": "missing",
   "fotos": "missing",
   "descripcion": "missing"
  },
  "status": "celeste"
 },
 {
  "num": 27,
  "responsable": "Cecilia",
  "respColor": "#7257c9",
  "respInit": "C",
  "owner": "",
  "phone": "",
  "fecha": "25-04-26",
  "propiedad": "Necochea N°731 e/34 y 35. Mirna",
  "valor": "USD 140.000 (se vende sin muebles)",
  "autorizacion": "sí",
  "cartel": "Sí, Conrado",
  "fotos": "sí, Arom",
  "descripcion": "sí, Ceci",
  "tasacion": "Silvia y Ceci",
  "link": "",
  "flags": [],
  "steps": {
   "tasacion": "done",
   "autorizacion": "done",
   "cartel": "done",
   "fotos": "done",
   "descripcion": "done"
  },
  "status": "negro"
 },
 {
  "num": 26,
  "responsable": "Conrado",
  "respColor": "#15784f",
  "respInit": "C",
  "owner": "",
  "phone": "",
  "fecha": "22-04-26",
  "propiedad": "Complejo: “Pampa Mansa” Av del Plata e/ Calampayo y los Condores. Oscar Dipaola.",
  "valor": "usd 680.000",
  "autorizacion": "no",
  "cartel": "no",
  "fotos": "sí, Con",
  "descripcion": "sí, Con y Ceci supervisó",
  "tasacion": "a cargo de Silvia",
  "link": "",
  "flags": [],
  "steps": {
   "tasacion": "done",
   "autorizacion": "missing",
   "cartel": "missing",
   "fotos": "done",
   "descripcion": "done"
  },
  "status": "rojo"
 },
 {
  "num": 25,
  "responsable": "Paul",
  "respColor": "#0e8a8a",
  "respInit": "P",
  "owner": "",
  "phone": "",
  "fecha": "21-04-26",
  "propiedad": "Complejo “Runa Moraira” Victoria entre virazón y sosa (Emanuel)",
  "valor": "No",
  "autorizacion": "El dueño lo va trabajar de forma Particular",
  "cartel": "no",
  "fotos": "no Descripción  no",
  "descripcion": "no",
  "tasacion": "22-04 , 17hs. Silvia y Pablo",
  "link": "",
  "flags": [
   "suspendido"
  ],
  "steps": {
   "tasacion": "done",
   "autorizacion": "partial",
   "cartel": "missing",
   "fotos": "missing",
   "descripcion": "missing"
  },
  "status": "pausa"
 },
 {
  "num": 24,
  "responsable": "Paul",
  "respColor": "#0e8a8a",
  "respInit": "P",
  "owner": "",
  "phone": "",
  "fecha": "21-04-26",
  "propiedad": "Fondo de comercio “El Nido”",
  "valor": "$ 40.000.000",
  "autorizacion": "no porque es una ayuda al propietario",
  "cartel": "no se pone",
  "fotos": "si Arom",
  "descripcion": "Si Paul",
  "tasacion": "No",
  "link": "",
  "flags": [],
  "steps": {
   "tasacion": "missing",
   "autorizacion": "missing",
   "cartel": "na",
   "fotos": "done",
   "descripcion": "done"
  },
  "status": "rojo"
 },
 {
  "num": 23,
  "responsable": "Fabiana",
  "respColor": "#c2861a",
  "respInit": "F",
  "owner": "Guillermo Zukowski",
  "phone": "1134748804",
  "fecha": "20/04",
  "propiedad": "Lote Punta del Este e/ 40 y 41",
  "valor": "USD 45.000",
  "autorizacion": "Si, Faby",
  "cartel": "si, Pablo",
  "fotos": "si",
  "descripcion": "si, https://www.silviafernandezpropiedades.com.ar/propiedad/7962268",
  "tasacion": "Silvia y pablo",
  "link": "https://www.silviafernandezpropiedades.com.ar/propiedad/7962268",
  "flags": [],
  "steps": {
   "tasacion": "done",
   "autorizacion": "done",
   "cartel": "done",
   "fotos": "done",
   "descripcion": "done"
  },
  "status": "negro"
 },
 {
  "num": 22,
  "responsable": "Fabiana",
  "respColor": "#c2861a",
  "respInit": "F",
  "owner": "",
  "phone": "",
  "fecha": "18-04-26",
  "propiedad": "Condominios Solares. Unidad n 29",
  "valor": "USD 130.000",
  "autorizacion": "sí, firmada (está en el grupo e wpp)",
  "cartel": "no lleva cartel",
  "fotos": "si",
  "descripcion": "si - https://www.silviafernandezpropiedades.com.ar/propertyDetail/7992332",
  "tasacion": "Silvia y Pablo",
  "link": "https://www.silviafernandezpropiedades.com.ar/propertyDetail/7992332",
  "flags": [],
  "steps": {
   "tasacion": "done",
   "autorizacion": "done",
   "cartel": "na",
   "fotos": "done",
   "descripcion": "done"
  },
  "status": "negro"
 },
 {
  "num": 21,
  "responsable": "Pablo",
  "respColor": "#2563eb",
  "respInit": "P",
  "owner": "",
  "phone": "",
  "fecha": "17-04-26",
  "propiedad": "43 e/Punta del Este y 1 (una casa arriba y otra abajo). Marcela A. Quinteros",
  "valor": "175.000",
  "autorizacion": "sí",
  "cartel": "sí, pablo",
  "fotos": "sí, Pablo",
  "descripcion": "sí, Ceci",
  "tasacion": "si, Silvia y Pablo.",
  "link": "",
  "flags": [],
  "steps": {
   "tasacion": "done",
   "autorizacion": "done",
   "cartel": "done",
   "fotos": "done",
   "descripcion": "done"
  },
  "status": "negro"
 },
 {
  "num": 20,
  "responsable": "Cecilia",
  "respColor": "#7257c9",
  "respInit": "C",
  "owner": "",
  "phone": "",
  "fecha": "16-04-26",
  "propiedad": "Apart Fueguia Santa Maria 444 e/ El Ceibo y Garay Pampas",
  "valor": "Usd 650.000. AÚN NO DECIDIERON PONERLO EN VENTA",
  "autorizacion": "no",
  "cartel": "no se pone cartel porque el dueño no quiere",
  "fotos": "no",
  "descripcion": "",
  "tasacion": "si Silvia y Pablo",
  "link": "",
  "flags": [
   "suspendido"
  ],
  "steps": {
   "tasacion": "done",
   "autorizacion": "missing",
   "cartel": "na",
   "fotos": "missing",
   "descripcion": "missing"
  },
  "status": "pausa"
 },
 {
  "num": 19,
  "responsable": "",
  "respColor": "#8a978f",
  "respInit": "·",
  "owner": "",
  "phone": "",
  "fecha": "13-04-26",
  "propiedad": "40 entre san clemente y monte hermoso n1027 (casa naranja)",
  "valor": "85.000 usd",
  "autorizacion": "",
  "cartel": "",
  "fotos": "",
  "descripcion": "",
  "tasacion": "se hizo la tasación (esperando confirmación del dueño)",
  "link": "",
  "flags": [
   "suspendido"
  ],
  "steps": {
   "tasacion": "partial",
   "autorizacion": "missing",
   "cartel": "missing",
   "fotos": "missing",
   "descripcion": "missing"
  },
  "status": "pausa"
 },
 {
  "num": 18,
  "responsable": "Pablo",
  "respColor": "#2563eb",
  "respInit": "P",
  "owner": "",
  "phone": "",
  "fecha": "12-04-26",
  "propiedad": "Lote san clemente e/29 y 30 (amigo de Pablo)",
  "valor": "USD 40.000",
  "autorizacion": "no, porque es amigo de Pablo",
  "cartel": "sí, Pablo",
  "fotos": "sí, pablo",
  "descripcion": "sí, Ceci",
  "tasacion": "sí",
  "link": "",
  "flags": [],
  "steps": {
   "tasacion": "done",
   "autorizacion": "missing",
   "cartel": "done",
   "fotos": "done",
   "descripcion": "done"
  },
  "status": "rojo"
 },
 {
  "num": 16,
  "responsable": "Curly",
  "respColor": "#b8791b",
  "respInit": "C",
  "owner": "",
  "phone": "",
  "fecha": "10-04",
  "propiedad": "Complejo de cabañas en 30 e/ mar azul y playa Ciromare",
  "valor": "1.500.000",
  "autorizacion": "si",
  "cartel": "no se pone",
  "fotos": "si",
  "descripcion": "siComplejo | Silvia Fernández Inmobiliaria",
  "tasacion": "silvia",
  "link": "",
  "flags": [],
  "steps": {
   "tasacion": "done",
   "autorizacion": "done",
   "cartel": "na",
   "fotos": "done",
   "descripcion": "done"
  },
  "status": "negro"
 },
 {
  "num": 15,
  "responsable": "",
  "respColor": "#8a978f",
  "respInit": "·",
  "owner": "",
  "phone": "",
  "fecha": "09-04",
  "propiedad": "punta del indio e/34 y 35 (Guillermina vacaz)",
  "valor": "USD 67.000",
  "autorizacion": "los dueños evalúan si ponerla a la venta",
  "cartel": "",
  "fotos": "",
  "descripcion": "",
  "tasacion": "Silvia y pablo",
  "link": "",
  "flags": [],
  "steps": {
   "tasacion": "done",
   "autorizacion": "done",
   "cartel": "missing",
   "fotos": "missing",
   "descripcion": "missing"
  },
  "status": "celeste"
 },
 {
  "num": 14,
  "responsable": "",
  "respColor": "#8a978f",
  "respInit": "·",
  "owner": "",
  "phone": "",
  "fecha": "09-04",
  "propiedad": "6759059. calle 40 e/Viña del mar y Copacabana. Propiedad vieja que ahora se debe publicar por separado el lote de la casa. (Mustang ranch)",
  "valor": "Usd 120 la casa y USD 45 el lote",
  "autorizacion": "sí.",
  "cartel": "sí, Con",
  "fotos": "Sí",
  "descripcion": "de lote, hecha a cargo de Pablo. Casa descripción Ceci.",
  "tasacion": "",
  "link": "",
  "flags": [],
  "steps": {
   "tasacion": "missing",
   "autorizacion": "done",
   "cartel": "done",
   "fotos": "done",
   "descripcion": "done"
  },
  "status": "rojo"
 },
 {
  "num": 13,
  "responsable": "Conrado",
  "respColor": "#15784f",
  "respInit": "C",
  "owner": "",
  "phone": "",
  "fecha": "09-04",
  "propiedad": "Departamento en Las Gaviotas, “Solari y las Gaviotas”",
  "valor": "Usd 130.000",
  "autorizacion": "ya está",
  "cartel": "",
  "fotos": "pablo ya sacó las fotos",
  "descripcion": "con https://www.silviafernandezpropiedades.com.ar/propiedad/7992332",
  "tasacion": "Silvia y Pablo",
  "link": "https://www.silviafernandezpropiedades.com.ar/propiedad/7992332",
  "flags": [],
  "steps": {
   "tasacion": "done",
   "autorizacion": "done",
   "cartel": "missing",
   "fotos": "done",
   "descripcion": "done"
  },
  "status": "rojo"
 },
 {
  "num": 12,
  "responsable": "",
  "respColor": "#8a978f",
  "respInit": "·",
  "owner": "",
  "phone": "",
  "fecha": "06-04-26",
  "propiedad": "LOTE NUEVO EN PAMPAS! Av del Plata e/sta maría y querandíes",
  "valor": "USd 50.000",
  "autorizacion": "sí, Silvia",
  "cartel": "sí, Con",
  "fotos": "Sí, Pablo",
  "descripcion": "sí, Pablo",
  "tasacion": "Silvia",
  "link": "",
  "flags": [],
  "steps": {
   "tasacion": "done",
   "autorizacion": "done",
   "cartel": "done",
   "fotos": "done",
   "descripcion": "done"
  },
  "status": "negro"
 },
 {
  "num": 11,
  "responsable": "",
  "respColor": "#8a978f",
  "respInit": "·",
  "owner": "",
  "phone": "",
  "fecha": "04-04-26",
  "propiedad": "José Ingenieros n17 (Mar de las Pampas)",
  "valor": "USD 220.000",
  "autorizacion": "Sí, Paul",
  "cartel": "Sí, Con",
  "fotos": "Sí, Pablo",
  "descripcion": "Sí, Arom",
  "tasacion": "Silvia",
  "link": "",
  "flags": [],
  "steps": {
   "tasacion": "done",
   "autorizacion": "done",
   "cartel": "done",
   "fotos": "done",
   "descripcion": "done"
  },
  "status": "negro"
 },
 {
  "num": 10,
  "responsable": "",
  "respColor": "#8a978f",
  "respInit": "·",
  "owner": "",
  "phone": "",
  "fecha": "01-04-26",
  "propiedad": "Calle 36 y punta del indio",
  "valor": "USD 139.000",
  "autorizacion": "si Pablo",
  "cartel": "sí",
  "fotos": "Sí.  Pablo sacó fotos y video.",
  "descripcion": "sí, Arom",
  "tasacion": "Pablo",
  "link": "",
  "flags": [],
  "steps": {
   "tasacion": "done",
   "autorizacion": "done",
   "cartel": "done",
   "fotos": "done",
   "descripcion": "done"
  },
  "status": "negro"
 },
 {
  "num": 9,
  "responsable": "",
  "respColor": "#8a978f",
  "respInit": "·",
  "owner": "",
  "phone": "",
  "fecha": "Marzo",
  "propiedad": "La Elegida (complejo). calle 41 e/punta del indio y viña del mar",
  "valor": "USD 650",
  "autorizacion": "Sí, Silvia.",
  "cartel": "no se pone (los dueños no quieren que se enteren los empleados)",
  "fotos": "sí, Pablo",
  "descripcion": "sí, Ceci",
  "tasacion": "Silvia y pablo",
  "link": "",
  "flags": [],
  "steps": {
   "tasacion": "done",
   "autorizacion": "done",
   "cartel": "na",
   "fotos": "done",
   "descripcion": "done"
  },
  "status": "negro"
 },
 {
  "num": 8,
  "responsable": "",
  "respColor": "#8a978f",
  "respInit": "·",
  "owner": "",
  "phone": "",
  "fecha": "28-03-26",
  "propiedad": "CARILÓ. Cerezo n°731",
  "valor": "Usd230",
  "autorizacion": "Por ahora no se va a hacer",
  "cartel": "si Paul",
  "fotos": "Sí, Pablo",
  "descripcion": "Sí, Ceci",
  "tasacion": "Silvia y Pablo",
  "link": "",
  "flags": [],
  "steps": {
   "tasacion": "done",
   "autorizacion": "partial",
   "cartel": "done",
   "fotos": "done",
   "descripcion": "done"
  },
  "status": "celeste"
 },
 {
  "num": 7,
  "responsable": "",
  "respColor": "#8a978f",
  "respInit": "·",
  "owner": "",
  "phone": "",
  "fecha": "27-03-26",
  "propiedad": "Copacabana e/39 y 40 (tranquera blanca). TODAVÍA NO DECIDIÓ VENDARLA CON NOSOTROS",
  "valor": "",
  "autorizacion": "",
  "cartel": "",
  "fotos": "",
  "descripcion": "",
  "tasacion": "Silvia y Pablo",
  "link": "",
  "flags": [
   "suspendido"
  ],
  "steps": {
   "tasacion": "done",
   "autorizacion": "missing",
   "cartel": "missing",
   "fotos": "missing",
   "descripcion": "missing"
  },
  "status": "pausa"
 },
 {
  "num": 6,
  "responsable": "",
  "respColor": "#8a978f",
  "respInit": "·",
  "owner": "",
  "phone": "",
  "fecha": "26-03-26",
  "propiedad": "36 e/ Necochea y Miramar (video en equipo).",
  "valor": ". LA DUEÑA DIJO QUE LO TIENE QUE PENSAR CON EL MARIDO Y NOS AVISA.",
  "autorizacion": "pablo la tiene que hacer",
  "cartel": "",
  "fotos": "PABLO TIENE QUE SACAR LAS FOTOS. AÚN NO ESTÁN",
  "descripcion": "",
  "tasacion": "Pablo. hay que sacar foto y ratificar valor. LA DUEÑA DIJO QUE LO TIENE QUE PENSAR CON EL MARIDO Y NOS AVISA.",
  "link": "",
  "flags": [],
  "steps": {
   "tasacion": "done",
   "autorizacion": "done",
   "cartel": "missing",
   "fotos": "done",
   "descripcion": "missing"
  },
  "status": "rojo"
 },
 {
  "num": 5,
  "responsable": "",
  "respColor": "#8a978f",
  "respInit": "·",
  "owner": "",
  "phone": "",
  "fecha": "24-03",
  "propiedad": "Copacabana e/34 y 35 (Mar Azul). 2 chalet contiguos. ID. 7876191",
  "valor": "Usd 147.000",
  "autorizacion": "sí (impresa en mar azul)",
  "cartel": "sí",
  "fotos": "sí. Arom",
  "descripcion": "sí, Arom",
  "tasacion": "Silvia",
  "link": "",
  "flags": [],
  "steps": {
   "tasacion": "done",
   "autorizacion": "done",
   "cartel": "done",
   "fotos": "done",
   "descripcion": "done"
  },
  "status": "negro"
 },
 {
  "num": 4,
  "responsable": "Cecilia",
  "respColor": "#7257c9",
  "respInit": "C",
  "owner": "Daniel y Margarita cel",
  "phone": "1153233826",
  "fecha": "24-03-26",
  "propiedad": "44 e/ Mar Azul y Mar del Plata (2 casas). HAY QUE VOLVER A SACAR FOTOS. AÚN NO HAY LLAVES. me comuniqué con la dueña 18/05 dentro de 15 días viene el marido.",
  "valor": "Usd 250.000",
  "autorizacion": "Sí, firmada. Sup cub. 240.91mts2. Lote: 950mts2",
  "cartel": "La dueña NO QUIERE QUE LE COLOQUEN CARTEL",
  "fotos": "Sí. Arom y Pablo (Con le envió a Arom un link con fotos).",
  "descripcion": "sí",
  "tasacion": "Silvia",
  "link": "",
  "flags": [],
  "steps": {
   "tasacion": "done",
   "autorizacion": "done",
   "cartel": "na",
   "fotos": "done",
   "descripcion": "done"
  },
  "status": "negro"
 },
 {
  "num": 3,
  "responsable": "",
  "respColor": "#8a978f",
  "respInit": "·",
  "owner": "",
  "phone": "",
  "fecha": "24-03-26",
  "propiedad": "Necochea e/ 43 y 44. Cristina (Alejandra mostró casa)",
  "valor": "Usd 145.000",
  "autorizacion": "sí, firmada. Sup cub: 86,16mts2 Lote: 350mts2",
  "cartel": "si Pablo",
  "fotos": "sí, Pablo.",
  "descripcion": "sí. Cecilia",
  "tasacion": "Silvia y Pablo",
  "link": "",
  "flags": [],
  "steps": {
   "tasacion": "done",
   "autorizacion": "done",
   "cartel": "done",
   "fotos": "done",
   "descripcion": "done"
  },
  "status": "negro"
 },
 {
  "num": 2,
  "responsable": "Cecilia",
  "respColor": "#7257c9",
  "respInit": "C",
  "owner": "",
  "phone": "",
  "fecha": "25-03-26",
  "propiedad": "Copacabana e/43 y 44. Id 7886629 . (MAXI)",
  "valor": "USD125.000",
  "autorizacion": "A CARGO DE SILVIA",
  "cartel": "Sí, Con",
  "fotos": "sí",
  "descripcion": "sí",
  "tasacion": "Silvia y Pablo",
  "link": "",
  "flags": [],
  "steps": {
   "tasacion": "done",
   "autorizacion": "done",
   "cartel": "done",
   "fotos": "done",
   "descripcion": "done"
  },
  "status": "negro"
 },
 {
  "num": 1,
  "responsable": "Cecilia",
  "respColor": "#7257c9",
  "respInit": "C",
  "owner": "",
  "phone": "",
  "fecha": "20-03-26",
  "propiedad": "Complejo. Calle 35 e/Copacabana y punta del Este. 7 cabañas. (cerca de la casa de pablo)",
  "valor": "USD 650",
  "autorizacion": "A CARGO DE SILVIA",
  "cartel": "sí, Con",
  "fotos": "sí.",
  "descripcion": "sí",
  "tasacion": "",
  "link": "",
  "flags": [],
  "steps": {
   "tasacion": "missing",
   "autorizacion": "done",
   "cartel": "done",
   "fotos": "done",
   "descripcion": "done"
  },
  "status": "rojo"
 }
];
